In [ ]:
from google.colab import files 
uploaded = files.upload()

In [ ]:

from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pandas as pd 
import io 
  
data = pd.read_csv('lab4.csv') 
data.head()

In [ ]:
data.info()

In [7]:
data.describe()

Unnamed: 0             0              1             2             3  \
count  10868.000000  1.086800e+04   10868.000000  1.086800e+04  1.086800e+04   
mean    5433.500000  5.412632e+04    8076.913876  1.002482e+04  7.096159e+03   
std     3137.465697  1.011696e+05   19019.471235  5.078501e+04  2.836619e+04   
min        0.000000  0.000000e+00       0.000000  0.000000e+00  0.000000e+00   
25%     2716.750000  1.125700e+04    1140.000000  6.570000e+02  6.910000e+02   
50%     5433.500000  2.182000e+04    4211.000000  3.053500e+03  3.075000e+03   
75%     8150.250000  6.079300e+04    7313.250000  3.901500e+03  3.662000e+03   
max    10867.000000  2.290304e+06  710311.000000  1.797398e+06  1.853743e+06   

                  4             5             6             7             8  \
count  1.086800e+04  1.086800e+04  1.086800e+04  1.086800e+04  1.086800e+04   
mean   8.952651e+03  4.358067e+03  7.718305e+03  3.839658e+03  5.029475e+03   
std    5.546638e+04  2.542380e+04  5.322195e+04  1.655496e+04  1.970269e+04   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    8.967500e+02  5.560000e+02  4.390000e+02  4.840000e+02  8.165000e+02   
50%    3.139000e+03  2.539000e+03  2.729000e+03  2.399500e+03  3.169500e+03   
75%    4.291750e+03  3.335000e+03  3.309000e+03  3.295000e+03  4.697750e+03   
max    1.633527e+06  1.766915e+06  1.773856e+06  1.086639e+06  1.123828e+06   

       ...             f9             fa             fb            fc  \
count  ...   10868.000000   10868.000000   10868.000000  10868.000000   
mean   ...    2003.397129    2240.809993    1792.368513   3269.539750   
std    ...    7593.041452    9265.912957    5599.736544   3664.695393   
min    ...       0.000000       0.000000       0.000000      0.000000   
25%    ...     331.000000     297.000000     316.000000    670.000000   
50%    ...     803.000000     701.000000     760.000000   2577.000000   
75%    ...    3100.000000    3102.000000    3103.000000   3273.000000   
max    ...  228692.000000  244977.000000  227158.000000  86938.000000   

                  fd             fe             ff            ??  \
count   10868.000000   10868.000000   10868.000000  1.086800e+04   
mean     2374.210986    3066.739510   15793.226077  4.986941e+05   
std      7853.044764    5036.446951   22896.046205  7.203975e+05   
min         0.000000       0.000000       0.000000  0.000000e+00   
25%       343.000000     467.750000    3139.750000  8.901000e+03   
50%       836.000000    2402.000000    6844.500000  1.729600e+04   
75%      3142.000000    3243.000000   16550.500000  1.490076e+06   
max    213004.000000  192296.000000  733486.000000  1.416540e+07   

               size         Class  
count  10868.000000  10868.000000  
mean       3.769535      4.017851  
std        3.012936      2.684621  
min        0.090744      1.000000  
25%        0.705811      2.000000  
50%        3.521769      3.000000  
75%        6.842773      6.000000  
max       45.028320      9.000000  

[8 rows x 260 columns]

In [8]:
data = data.drop(["ID"], axis=1) 
data = data.drop(["Unnamed: 0"], axis=1) 
data.head()

0     1     2     3     4     5     6     7     8     9  ...    f9  \
0  601905  3905  2816  3832  3345  3242  3650  3201  2965  3205  ...  3101   
1   39755  8337  7249  7186  8663  6844  8420  7589  9291   358  ...   439   
2   93506  9542  2568  2438  8925  9330  9007  2342  9107  2457  ...  2242   
3   21091  1213   726   817  1257   625   550   523  1078   473  ...   485   
4   19764   710   302   433   559   410   262   249   422   223  ...   350   

     fa    fb    fc    fd     fe     ff     ??      size  Class  
0  3211  3097  2758  3099   2759   5753   1824  4.234863      9  
1   281   302  7639   518  17001  54902   8588  5.538818      2  
2  2885  2863  2471  2786   2680  49144    468  3.887939      9  
3   462   516  1133   471    761   7998  13940  0.574219      1  
4   209   239   653   221    242   2199   9008  0.370850      8  

[5 rows x 259 columns]

In [9]:
# contains no null values
incomplete_rows = data[data.isnull().any(axis=1)].head()
incomplete_rows

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0a, 0b, 0c, 0d, 0e, 0f, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 1a, 1b, 1c, 1d, 1e, 1f, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 2a, 2b, 2c, 2d, 2e, 2f, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 3a, 3b, 3c, 3d, 3e, 3f, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 4a, 4b, 4c, 4d, 4e, 4f, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 5a, 5b, 5c, 5d, 5e, 5f, 60, 61, 62, 63, ...]
Index: []

[0 rows x 259 columns]

In [10]:
data["Class"].value_counts()

3    2942
2    2478
1    1541
8    1228
9    1013
6     751
4     475
7     398
5      42
Name: Class, dtype: int64

In [11]:
# Use stratified sampling to create an 80-20 train-test split
feature = data.drop(['Class'], axis = 1)
target = data['Class']

# spliting data 20% to test and rest to train
train_data_i,test_data_i, train_data_o, test_data_o = train_test_split(feature, target, test_size = 0.2,stratify = target, random_state = 42)
print('Train input size ', train_data_i.shape)
print('Test input size ', test_data_i.shape)
print('Train output size ', train_data_o.shape)
print('Test output size ', test_data_o.shape)

Train input size  (8694, 258)
Test input size  (2174, 258)
Train output size  (8694,)
Test output size  (2174,)


In [12]:
train_data_o.head()

3733    8
2280    8
1845    2
7694    6
8128    3
Name: Class, dtype: int64

In [13]:
#standdardize the data
scale = StandardScaler().fit(train_data_i)
train_data_i = scale.transform(train_data_i)
test_data_i = scale.transform(test_data_i)

In [14]:
train_data_i

array([[-0.33652224, -0.38883088, -0.18929193, ..., -0.5872835 ,
        -0.6793142 , -1.1285937 ],
       [-0.03491896, -0.33576001, -0.17334224, ..., -0.38776342,
        -0.67935855, -1.06127222],
       [-0.10235753,  0.0931812 , -0.0247202 , ...,  1.8221795 ,
        -0.67505114,  1.28705957],
       ...,
       [-0.27244919, -0.31193873, -0.17487059, ..., -0.3363354 ,
        -0.64157868, -1.03355161],
       [-0.04798623,  0.38794324,  0.20053477, ...,  2.01546458,
        -0.67562768,  1.10489555],
       [-0.41902173, -0.14355598, -0.13284102, ..., -0.38724742,
         1.3818258 ,  1.01777363]])

In [15]:
import matplotlib as mp1
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
import numpy as np

# Find the best Logistic Regression model that can solve this problem

#L1 penalty

C = [0.001,0.01,0.1,1,10,100,1000]
l1_reg = LogisticRegressionCV(Cs=C, random_state=42,max_iter=30, solver='saga', penalty='l1',class_weight='balanced')
l1_reg.fit(train_data_i,train_data_o)
l1_best_C = l1_reg.C_
l1_best_train_score = np.mean(cross_val_score(l1_reg,train_data_i,train_data_o,cv=3,scoring="accuracy"))
print('Best C : ',l1_best_C[0])
print('Training Score : ',l1_best_train_score)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/Users/deepankarsingh/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
  File "<ipython-input-15-849716200de5>", line 15, in <module>
    l1_best_train_score = np.mean(cross_val_score(l1_reg,train_data_i,train_data_o,cv=3,scoring="accuracy"))
  File "/Users/deepankarsingh/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 390, in cross_val_score
    error_score=error_score)
  File "/Users/deepankarsingh/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 236, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/Users/deepankarsingh/opt/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1007, in __call__
    while self.dispatch_one_batch(iterator):
  File "/Users/deepankarsingh/opt/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 835, in dispatch_one_batch
    self._dispatch

KeyboardInterrupt: 

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np

In [ ]:
l1_pred = l1_reg.predict(test_data_i)
count_misclassified = (test_data_o != l1_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
print(accuracy_score(test_data_o,l1_pred))


In [ ]:
cm = confusion_matrix(test_data_o,l1_pred)
cm

In [22]:
from sklearn.linear_model import LogisticRegression
l2_reg = LogisticRegressionCV(Cs=C, random_state=42,max_iter=30, solver='saga', penalty='l2',class_weight='balanced')
l2_reg.fit(train_data_i,train_data_o)
l2_best_C = l2_reg.C_
l2_best_train_score = np.mean(cross_val_score(l2_reg,train_data_i,train_data_o,cv=3,scoring="accuracy"))
print('Best C : ',l2_best_C[0])
print('Training Score : ',l2_best_train_score)

Best C :  1000.0
Training Score :  0.8572578789970094


In [24]:
l2_pred = l2_reg.predict(test_data_i)
count_misclassified = (test_data_o != l2_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
print(accuracy_score(test_data_o,l2_pred))


Misclassified samples: 255
0.8827046918123275


In [26]:
cm = confusion_matrix(test_data_o,l2_pred)
cm

array([[240,   2,   3,  12,   2,   3,   1,  41,   4],
       [ 28, 413,   8,   5,   2,  19,   1,   9,  11],
       [  0,   0, 588,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  92,   0,   3,   0,   0,   0],
       [  0,   0,   0,   3,   5,   0,   0,   0,   0],
       [  7,   0,   0,  22,   4, 104,   1,   8,   4],
       [  0,   0,   0,   0,   2,   3,  75,   0,   0],
       [  7,   0,   0,   9,   2,   1,   0, 225,   2],
       [  2,   1,   2,   2,   0,   4,   4,  11, 177]])

In [2]:
en_reg = LogisticRegressionCV(Cs=C, random_state=42,max_iter=30, solver='saga', penalty='elasticnet',l1_ratios=[0.0,0.25,0.5,0.75,1.0],class_weight='balanced')
en_reg.fit(train_data_i,train_data_o)
en_best_train_score = np.mean(cross_val_score(en_reg,train_data_i,train_data_o,cv=3,scoring="accuracy"))
en_best_C = en_reg.C_
print('Best C : ',en_best_C)
print('Training Score : ',en_best_train_score)


NameError: ignored

In [ ]:
en_pred = en_reg.predict(test_data_i)
count_misclassified = (test_data_o != en_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
print(accuracy_score(test_data_o,en_pred))

Misclassified samples: 182
0.9162833486660533


In [1]:
cm = confusion_matrix(test_data_o,en_pred)
cm

NameError: ignored

In [ ]:
from sklearn.model_selection import GridSearchCV
parameter_space = {
    'hidden_layer_sizes': [(20),(30),(50)],
    'activation': ['relu'],
    'solver': ['sgd', 'adam'],
    'alpha': [0.00001,0.0001, 0.05],
     'max_iter':[50,100,200]
    'learning_rate': ['constant','adaptive'],
}
multi_l_p = GridSearchCV(MLPClassifier, parameter_space, cv=5)
clf.fit(train_data_i, train_data_o)

In [ ]:
print('Best parameters found:\n', multi_l_p.best_params_)

Best parameters found:
 {'activation': 'tanh', 'alpha': 0.0001, 'hidden_layer_sizes': 20, 'learning_rate': 'constant', 'max_iter': 30, 'solver': 'adam'}


In [ ]:
y_pred = multi_l_p.predict(test_data_i)

In [ ]:
accuracy_score(test_data_o,y_pred)

0.9162833486660533

In [ ]:
count_misclassified = (test_data_o != y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
cm = confusion_matrix(test_data_o,y_pred)

Misclassified samples: 182


In [ ]:
cm

array([[285,   2,   0,   2,   0,   5,   1,   9,   4],
       [ 15, 436,   6,   3,   0,   9,   3,  10,  14],
       [  0,   0, 588,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  85,   0,   2,   0,   8,   0],
       [  0,   0,   0,   3,   0,   0,   4,   1,   0],
       [ 10,   0,   4,   8,   0, 114,   1,   8,   5],
       [  2,   0,   1,   0,   0,   2,  74,   1,   0],
       [  7,   0,   1,   4,   0,   2,   0, 228,   4],
       [  7,   2,   2,   0,   0,   0,   0,  10, 182]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
parameters = {
    'n_estimators'      : [320,330,340,500],
    'max_depth'         : [9, 10, 11, 12,100],
    'random_state'      : [0],
    'criterion' :['gini','entropy']
}
clf = GridSearchCV(RandomForestClassifier(class_weight='balanced'), parameters, cv=5)
clf.fit(train_data_i, train_data_o)
print('Best parameters found:\n', clf.best_params_)


In [ ]:
pred = clf.predict(test_data_i)
accuracy_score(test_data_o,pred)

In [ ]:
count_misclassified = (test_data_o != pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
cm = confusion_matrix(test_data_o,pred)
cm